Ruzanna/ mr clean
abdullaabdukulov/02-Data-Science-My-Mr-Clean- pull request #20
Opened 2024-03-24 20:00 UTC by RuzannaRu

2024-03-24 20:12 UTC, RuzannaRu commented
.

2024-03-24 20:12 UTC, RuzannaRu commented
.

2024-03-24 20:13 UTC, RuzannaRu commented
ru

2024-03-25 10:58 UTC, abdullaabdukulov requested changes
O'tmadi sabablari:
1. Branch nomi ism_familya ko'rinishida bo'lishi kerak
2. tehnik vazifada berilgani kabi funskiyalarni to'liq yozmagansiz
3. vizualizatsiyani style yahshi emas

2024-03-25 10:58 UTC, closed without merging